### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by mahmoudhossam** [Pyeg/Ideas#7]
I'm a little bit confused as to what exactly is this organization.

Is this going to be a community like [eglug](http://eglug.org/) and [ubuntu-eg](http://www.ubuntu-eg.org/)? or this is only for collaboration on specific projects?

The [current README](https://github.com/Pyeg/Ideas/blob/master/README.md) doesn't explain much.

**Comment by gr33ndata** [comment]
Hi Mahmoud, Pyeg is meant to be an online place where we - as python developers - can gather, share ideas and collaborate on projects. We started using the Ideas repo to list ideas for projects the members think they may like to collaborate on and there is a need for them, but later on, we make it more flexible to discuss any ideas about the python development community we wish to build. 

In brief, we believe the best way for us to create a community for python developers, is to build such community around code, we better collaborate on coding rather than anything else.

**Comment by mahmoudhossam** [comment]
Thank you for clearing that up, Tarek.

Can you add this to the README or should I?

**Comment by gr33ndata** [comment]
Hi Mahmoud, I've updated the README file accordingly now, please feel free to edit or add anything here if you feel there is a need.

**Comment by mahmoudhossam** [comment]
Will do, thanks again.
